### ISSUE TITLE
Mapping for IEEE references in `misc` dataset to IEEE dataset

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#125]
There are 4 types of files, we need to implement a mapping for Types 1 and 2. Not sure what to do with Type 3 and 4.

* Type 1: they have an exact match in the IEEE dataset, the file path is used here.
* Type 2: they were IEEE-led but NOT IEEE standards! And therefore there is NO data in the IEEE data set. IEEE doesn't even have those on their own website. There are two cases of this which are actually ISO standards (I verified the standard titles).
* Type 3: Not found in the IEEE dataset. Document is available from IEEE online.
* Type 4: Not found anywhere, likely wrong.

## Type 1: have an exact match in the IEEE dataset

```yaml
reference.IEEE.1003-2.1992.xml: data/ISO_IEC_14515-2.yaml
reference.IEEE.1278-1.1995.xml: data/IEEE_1278-1.1995.yaml
reference.IEEE.1278-2.1995.xml: data/IEEE_1278-2.1995.yaml
reference.IEEE.1284-1.1997.xml: data/IEEE_1284-1.1997.yaml
reference.IEEE.1394.1995.xml: data/IEEE_1394.1995.yaml
reference.IEEE.754.1985.xml: data/ANSI_IEEE_754.1985.yaml
reference.IEEE.802-11.1999.xml: data/ANSI_IEEE_802-11.1999.yaml
reference.IEEE.802-11A.1999.xml: data/IEEE_802-11A.1999.yaml
reference.IEEE.802-11B.1999.xml: data/IEEE_802-11B.1999.yaml
reference.IEEE.802-11D.2001.xml: data/IEEE_802-11D.2001.yaml
reference.IEEE.802-11F.2003.xml: data/IEEE_P802-11F_D-6.yaml
reference.IEEE.802-11G.2003.xml: data/IEEE_802-11G.2003.yaml
reference.IEEE.802-11H.2003.xml: data/IEEE_802-11H.2003.yaml
reference.IEEE.802-11I.2004.xml: data/IEEE_802-11I.2004.yaml
reference.IEEE.802-12.1995.xml: data/IEEE_802-12.1995.yaml
reference.IEEE.802-1A.1990.xml: data/IEEE_802.1990.yaml
reference.IEEE.802-1D.1990.xml: data/IEEE_802-1D.1990.yaml
reference.IEEE.802-1G.1992.xml: data/IEEE_802-1G.1998.yaml
reference.IEEE.802-2.1984.xml: data/ANSI_IEEE_802-2.1985.yaml
reference.IEEE.802-2.1985.xml: data/ANSI_IEEE_802-2.1985.yaml
reference.IEEE.802-2.1989.xml: data/ISO_8802-2.yaml
reference.IEEE.802-2.1994.xml: data/IEEE_8802-2.1994.yaml
reference.IEEE.802-3.1985.xml: data/ANSI_IEEE_802-3.1985.yaml
reference.IEEE.802-3.1988.xml: data/ANSI_IEEE_802-3.yaml
reference.IEEE.802-3.1998.xml: data/IEEE_802-3.1998.yaml
reference.IEEE.802-4.1988.xml: data/ANSI_IEEE_802-4.1990.yaml
reference.IEEE.802-5.1989.xml: data/IEEE_802-5.1989.yaml
reference.IEEE.802-5.1995.xml: data/IEEE_802-5.1998.yaml
reference.IEEE.802-6.1990.xml: data/IEEE_802-6.1990.yaml
reference.IEEE.802.1990.xml: data/IEEE_802.1990.yaml
reference.IEEE.802.1QBV_2015.xml: data/IEEE_802-1QBV.2015.yaml
reference.IEEE.802.1Qcc-2018.xml: data/IEEE_802-1QCC.2018.yaml
reference.IEEE.P1363.1998.xml: data/IEEE_1363.2000.yaml
reference.IEEE.P1394A.1995.xml: data/IEEE_1394A.2000.yaml
reference.IEEE.P1394B.1995.xml: data/IEEE_1394B.2002.yaml
reference.IEEE.P802-1A.1989.xml: data/IEEE_802-11A.1999.yaml
reference.IEEE.P802-1Q.1998.xml: data/IEEE_802-1Q.1998.yaml
reference.IEEE.P802-3K.1992.xml: data/IEEE_802-3K.1992.yaml
reference.IEEE.P802-5D.1989.xml: data/ISO_IEC_8802-5.1992.yaml
reference.IEEE.P8021D.1989.xml: data/IEEE_802-5.1989.yaml
```

## Type 2: non-IEEE standards

```yaml
reference.IEEE.802-3.1990.xml: ISO/IEC 8802-3:1990
reference.IEEE.802-3.1996.xml: ISO/IEC 8802-3:1996
```

## Type 3: Not provided in IEEE bibliographic data set

```yaml
reference.IEEE.1003-1G.1997.xml: NOT AVAILABLE, https://standards.ieee.org/ieee/1003.1g/1397/
```

## Type 4: Unable to locate on the Internet

```yaml
reference.IEEE.802-1D.1991.xml: ONLY INTERNET SOURCE IS bibxml2
reference.IEEE.802-1D.1993.xml: ONLY INTERNET SOURCE IS bibxml2
reference.IEEE.802-1Y.1990.xml: NOT AVAILABLE, there is a 802.1Y but is a completely different document.
reference.IEEE.P802-3P.1992.xml: ONLY INTERNET SOURCE IS bibxml2
reference.IEEE.P8021A.1989.xml: ONLY INTERNET SOURCE IS bibxml2
```
