### ISSUE TITLE
Mapping for W3C references in `misc` dataset to W3C dataset

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#130]
Need to map:

```
reference.W3C.CR-rdf-schema.xml
reference.W3C.DSig-label.xml
reference.W3C.P3P-rdfschema.xml
reference.W3C.P3P.xml
reference.W3C.PICS-labels.xml
reference.W3C.PICS-rules.xml
reference.W3C.PICS-services.xml
reference.W3C.REC-RUBY.xml
reference.W3C.REC-XHTML.xml
reference.W3C.REC-rdf-syntax.xml
reference.W3C.REC-xml-1998.xml
reference.W3C.REC-xml-names.xml
reference.W3C.REC-xml.xml
reference.W3C.REC-xmlenc-core.xml
reference.W3C.REC-xmlschema-1.xml
reference.W3C.REC-xmlschema-2.xml
reference.W3C.REC-xslt.xml
reference.W3C.daml-oil-reference.xml
reference.W3C.soap11.xml
reference.W3C.soap12-part1.xml
reference.W3C.soap12-part2.xml
reference.W3C.xkms.xml
reference.W3C.xml-c14n.xml
reference.W3C.xmldsig-core.xml
reference.W3C.xmlenc-core.xml
reference.W3C.xpath.xml
```

**Comment by ronaldtse** [comment]
Mapping done:

```yaml
---
reference.W3C.CR-rdf-schema.xml: W3C CR-rdf-schema
reference.W3C.DSig-label.xml: W3C DSig-label
reference.W3C.P3P-rdfschema.xml: W3C P3P-rdfschema
reference.W3C.P3P.xml: W3C P3P
reference.W3C.PICS-labels.xml: W3C PICS-labels
reference.W3C.PICS-rules.xml: PICS-rules
reference.W3C.PICS-services.xml: PICS-services
reference.W3C.REC-RUBY.xml: W3C REC-RUBY
reference.W3C.REC-XHTML.xml: W3C REC-XHTML
reference.W3C.REC-rdf-syntax.xml: W3C REC-rdf-syntax
reference.W3C.REC-xml-1998.xml: W3C REC-xml-1998
reference.W3C.REC-xml-names.xml: W3C REC-xml-names
reference.W3C.REC-xml.xml: W3C REC-xml
reference.W3C.REC-xmlenc-core.xml: REC-xmlenc-core
reference.W3C.REC-xmlschema-1.xml: REC-xmlschema-1
reference.W3C.REC-xmlschema-2.xml: REC-xmlschema-2
reference.W3C.REC-xslt.xml: W3C REC-xslt-19991116
reference.W3C.daml-oil-reference.xml: W3C daml+oil-reference
reference.W3C.soap11.xml: W3C soap11
reference.W3C.soap12-part1.xml: W3C soap12-part1
reference.W3C.soap12-part2.xml: W3C soap12-part2
reference.W3C.xkms.xml: W3C xkms
reference.W3C.xml-c14n.xml: W3C xml-c14n
reference.W3C.xmldsig-core.xml: W3C xmldsig-core
reference.W3C.xmlenc-core.xml: W3C xmlenc-core
reference.W3C.xpath.xml: W3C xpath
```
