### ISSUE TITLE
Mapping for W3C references in `bibxml4` to W3C dataset

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#133]
[w3c-mapping.yaml.zip](https://github.com/ietf-ribose/bibxml-service/files/8099395/w3c-mapping.yaml.zip)

This mapping is not yet complete.

**Comment by strogonoff** [comment]
What’s the purpose of this mapping? Note, xml2rfc compatibility tool supports JSON import/export, so we can auto-compile mappings that can be imported into BibXML service.

**Comment by ronaldtse** [comment]
@strogonoff I'm confused on what you mean. What is "auto-compile" for the "xml2rfc compatibility tool"?

This mapping is intended to provide an accurate representation for every item in bibxml4 that exists in the new W3C data source. An automatic approach does not work for all items.

**Comment by strogonoff** [comment]
(Sorry, meant “convert YAML to JSON automatically”. We’ll deal with it…)

**Comment by ronaldtse** [comment]
@andrew2net the mapping is not done. The file I uploaded only has bibxml4 filenames but not the targets. Can you fill those in and upload the file here? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse do you mean mapping like:
```yaml
reference.W3C.07-WebData.xml:
reference.W3C.CR-2dcontext-20121217.xml: http://www.w3.org/TR/2012/CR-2dcontext-20121217
...
```
