### ISSUE TITLE
Unable to find "ISO 10589" through BibXML service

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#197]
As reported by @rjsparks :

> [A user noticed today that "ISO 10589" cannot be found using]
> the bibxml service UI, searching for "ISO 10589". Should that 
> search have found that document?
>
> (https://github.com/ietf-ribose/relaton-data-misc/blob/main/data/reference.ISO.10589.1992.yaml) 
> exists.

This may be an issue with the dataset currently encoding this document with incorrect identifiers:

https://github.com/ietf-ribose/relaton-data-misc/blob/8b34219ac802c27e9a3facbf58bfc9c3c5976262/data/reference.ISO.10589.1992.yaml#L14-L19

```yaml
- id: ISO 10589.1992
  type: IETF
  primary: true
- id: ISO.10589.1992
  type: IETF
  scope: anchor
```

We will need to figure out a better way of doing this (1) with indexing (2) with document identifier normalization.
