### ISSUE TITLE
Mapping diffs: NIST SP 500-116 is not using the new data

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#233]
## Problematic: NIST references

The BibXML Service needs to be fixed here.

For example, NIST SP 500-116 is available at:
https://github.com/relaton/relaton-data-nist/blob/main/data/NIST_SP_500-166.yaml

The BibXML content is not reflecting the correct data right now.
<img width="843" alt="Screenshot 2022-07-15 at 9 48 09 AM" src="https://user-images.githubusercontent.com/11865/179124723-9a9a2253-8956-4413-97cf-a22e3184cfe2.png">

From: https://github.com/ietf-ribose/bibxml-service/issues/222

**Comment by ronaldtse** [comment]
Actually this only applies to NIST SP 500-116.

**Comment by strogonoff** [comment]
Is that still the case? Screenshots may be outdated since sources change.

**Comment by ronaldtse** [comment]
I just checked and it is correct now:

https://dev.bibxml.org/public/rfc/bibxml2/reference.NIST.500-166.1989.xml

```xml
<reference target="https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication500-166.pdf" anchor="NIST_SP_500_166">
  <front>
    <title>Computer viruses and related threats</title>
    <author fullname="John P. Wack" surname="Wack" initials="P"/>
    <author fullname="Lisa J. Carnahan" surname="Carnahan" initials="J"/>
    <author>
      <organization abbrev="NIST">National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <country>US</country>
          <city>Gaithersburg</city>
        </postal>
      </address>
    </author>
    <date year="1989"/>
  </front>
  <seriesInfo name="NIST Special Publications (General)" value="NIST SP"/>
  <seriesInfo name="DOI" value="10.6028/NIST.SP.500-166"/>
</reference>
```

Thanks~

**Comment by ronaldtse** [comment]
But the `initials` in the `<author>` element is incorrect.

In https://github.com/relaton/relaton-data-nist/blob/bac0572d068cb45b2686ac6d7b50a23c15881d91/data/NIST_SP_500-166.yaml#L26-L45

```yaml
- person:
    name:
      forename:
      - content: John
        language:
        - en
        script:
        - Latn
      initial:
      - content: P
        language:
        - en
        script:
        - Latn
      surname:
        content: Wack
        language:
        - en
        script:
        - Latn
```

This person's name is technically "John P. Wack". There seems to be some problem in the mapping between Relaton => BibXML elements.

We need to check whether it is a relaton-nist / relaton-py issue or a new issue.
