### ISSUE TITLE
NIST SP 500-116 initials are wrong

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-service#243]
The `initials` in the `<author>` element is incorrect.

In https://github.com/relaton/relaton-data-nist/blob/bac0572d068cb45b2686ac6d7b50a23c15881d91/data/NIST_SP_500-166.yaml#L26-L45

```yaml
- person:
    name:
      forename:
      - content: John
        language:
        - en
        script:
        - Latn
      initial:
      - content: P
        language:
        - en
        script:
        - Latn
      surname:
        content: Wack
        language:
        - en
        script:
        - Latn
```

This person's name is technically "John P. Wack". There seems to be some problem in the mapping between Relaton => BibXML elements.

We need to check whether it is a relaton-nist / relaton-py issue or a new issue.

_Originally posted by @ronaldtse in https://github.com/ietf-ribose/bibxml-service/issues/233#issuecomment-1192538110_
